version: "2"

services:
  app:
    # image: raivieiraadriano92/docker-react-native
    image: raivieiraadriano92/docker-react-native:with-emulator
    ports:
      - "9090:9090"
      - "8081:8081"
    volumes:
      - .:/usr/src
      - ~/.gradle:/root/.gradle
      - /dev:/dev
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    # command: sh -c "for f in ~/.android/avd/*.avd/config.ini; do echo 'hw.keyboard=yes' >> \"$f\"; done"
    tty: true
    privileged: true
    environment:
      NODE_ENV: development
      DISPLAY: $DISPLAY
    links:
      - rctron

  rctron:
    image: cbsan/react
    restart: always
    tty: true
    ports:
      - "9091:9090"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "./m2:/usr/src/app"
    environment:
      DISPLAY: $DISPLAY
