version: '2'

services:
  app:
    image: raivieiraadriano92/docker-react-native:with-emulator #imagem COM emulador android
    #image: raivieiraadriano92/docker-react-native #imagem SEM emulador android
    volumes:
      - .:/usr/src
      - ~/.gradle:/root/.gradle
      - /dev:/dev
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    tty: true
    privileged: true
    environment:
      NODE_ENV: development
      DISPLAY: $DISPLAY