version: "2"

services:
  app:
    image: raivieiraadriano92/docker-react-native
    ports:
      - "9090:9090"
      - "8081:8081"
    volumes:
      - .:/usr/src
      - ~/.gradle:/root/.gradle
      - /dev:/dev
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    tty: true
    privileged: true
    environment:
      NODE_ENV: development
      DISPLAY: $DISPLAY
    links:
      - rctron

  rctron:
    image: cbsan/react
    restart: always
    tty: true
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      DISPLAY: $DISPLAY
